BASE_URL_JSON_PLACE_HOLDER_DEV="http://jsondev.lmslite.com"
BASE_URL_JSON_PLACE_HOLDER_LIVE="http://jsondev.lmslite.com"

BASE_URL_DEV="http://jsondev.lmslite.com"
ACCESS_TOKEN_DEV="token_dev"

BASE_URL_STAGING="http://jsondev.lmslite.com"
ACCESS_TOKEN_STAGING="token_staging"

BASE_URL_LIVE="http://jsondev.lmslite.com"
ACCESS_TOKEN_LIVE="token_live"